Force update for wtm_xk

diff --git a/.github/workflows/r30.yml b/.github/workflows/r30.yml
--- a/.github/workflows/r30.yml
+++ b/.github/workflows/r30.yml
@@ -86,8 +86,8 @@ jobs:
       - name: "Script - Run"
         run: |
           Rscript 'get_audiences.R' ${TF} "XK"
-          if [ -f status.txt ]; then
-            status=$(cat status.txt)
+          if [ -f status_${TF}.txt ]; then
+            status=$(cat status_${TF}.txt)
             if [ "$status" == "changes_detected" ]; then
               # Increment the resume count as work continues
               if [ -f resume_count_${TF}.txt ]; then
@@ -102,12 +102,18 @@ jobs:
               RESUME_COUNT=0
               echo "No changes detected. Resetting resume count to $RESUME_COUNT"
             fi
-            echo $RESUME_COUNT > resume_count_${TF}.txt
           else
-            echo "Status file not found. Defaulting to no changes."
-            RESUME_COUNT=0
-            echo $RESUME_COUNT > resume_count_${TF}.txt
+            echo "Status file for timeframe ${TF} not found. Defaulting to trying again."
+            if [ -f resume_count_${TF}.txt ]; then
+              RESUME_COUNT=$(cat resume_count_${TF}.txt)
+            else
+              RESUME_COUNT=0
+            fi
+            RESUME_COUNT=$((RESUME_COUNT + 1))
+            echo "Resume count increased to $RESUME_COUNT"
           fi
+          # Save updated resume count
+          echo $RESUME_COUNT > resume_count_${TF}.txt
         env:
           RESUME_COUNT: ${{ env.RESUME_COUNT }}
 
@@ -124,10 +130,19 @@ jobs:
             echo "Neither 'main' nor 'master' branch exists. Exiting."
             exit 1
           fi
-        
+
+          # Check if RESUME_COUNT is set
+          if [ -z "$RESUME_COUNT" ]; then
+            echo "RESUME_COUNT is not set. Using default value of 0."
+            RESUME_COUNT=0
+          fi
+          echo "Using Resume Count: $RESUME_COUNT"
+
           # Stage and commit all changes, including resume count
           git add -A
-          git commit -m "#${RESUME_COUNT} Resume ${TF} TF: $(date +"%Y-%m-%d %H:%M:%S")" || echo "No changes to commit"
-        
+          git commit -m "#$RESUME_COUNT Resume ${TF} TF: $(date +"%Y-%m-%d %H:%M:%S")" || echo "No changes to commit"
+
           # Force push changes to the determined branch
           git push --force origin $TARGET_BRANCH
+        env:
+          RESUME_COUNT: ${{ env.RESUME_COUNT }}
